name: Auto-trigger Codex via comment

on:
  pull_request:
    # PR作成・更新・再オープン・下書き→準備完了 で実行
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  issues: write          # ← コメント投稿に必要
  pull-requests: write   # ← 一部APIで必要になる場合に備え保険

jobs:
  comment-codex:
    # 同一リポジトリPRのみ対象（フォークPRはcodex-autocomment-forks.ymlで処理）
    if: >
      github.event.pull_request.head.repo.fork == false
      && !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Post "@codex review" comment
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo
            const issue_number = context.payload.pull_request.number
            const body = '@codex review'
            await github.rest.issues.createComment({ owner, repo, issue_number, body })
