name: Codex Review Discord Notification

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  notify-codex-review:
    runs-on: ubuntu-latest
    # Codexのbotユーザーからのコメント/レビューのみ通知
    if: github.actor == 'chatgpt-codex-connector[bot]'

    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # イベントタイプを判定
          EVENT_TYPE="${{ github.event_name }}"

          # PRの情報を取得
          if [ "$EVENT_TYPE" = "issue_comment" ]; then
            PR_NUMBER="${{ github.event.issue.number }}"
            PR_TITLE="${{ github.event.issue.title }}"
            PR_URL="${{ github.event.issue.html_url }}"
            COMMENT_BODY="${{ github.event.comment.body }}"
            COMMENT_URL="${{ github.event.comment.html_url }}"
          elif [ "$EVENT_TYPE" = "pull_request_review" ]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
            PR_TITLE="${{ github.event.pull_request.title }}"
            PR_URL="${{ github.event.pull_request.html_url }}"
            COMMENT_BODY="${{ github.event.review.body }}"
            COMMENT_URL="${{ github.event.review.html_url }}"
          elif [ "$EVENT_TYPE" = "pull_request_review_comment" ]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
            PR_TITLE="${{ github.event.pull_request.title }}"
            PR_URL="${{ github.event.pull_request.html_url }}"
            COMMENT_BODY="${{ github.event.comment.body }}"
            COMMENT_URL="${{ github.event.comment.html_url }}"
          fi

          # コメント本文を最初の200文字に制限
          COMMENT_PREVIEW=$(echo "$COMMENT_BODY" | head -c 200)
          if [ ${#COMMENT_BODY} -gt 200 ]; then
            COMMENT_PREVIEW="${COMMENT_PREVIEW}..."
          fi

          # JSON用にコメントをエスケープ
          COMMENT_PREVIEW_ESCAPED=$(echo "$COMMENT_PREVIEW" | jq -Rs .)
          PR_TITLE_ESCAPED=$(echo "$PR_TITLE" | jq -Rs .)

          # Discordに通知を送信
          curl -H "Content-Type: application/json" \
            -d "{
              \"embeds\": [{
                \"title\": \"🤖 Codex Review on PR #${PR_NUMBER}\",
                \"description\": ${PR_TITLE_ESCAPED},
                \"color\": 3447003,
                \"fields\": [
                  {
                    \"name\": \"Event Type\",
                    \"value\": \"${EVENT_TYPE}\",
                    \"inline\": true
                  },
                  {
                    \"name\": \"Repository\",
                    \"value\": \"${{ github.repository }}\",
                    \"inline\": true
                  },
                  {
                    \"name\": \"Comment Preview\",
                    \"value\": ${COMMENT_PREVIEW_ESCAPED}
                  }
                ],
                \"url\": \"${COMMENT_URL}\",
                \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
              }]
            }" \
            $DISCORD_WEBHOOK
