name: Codex auto-comment (fork PRs)

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment-codex-fork:
    # フォークPRのみ対象
    if: >
      github.event.pull_request.head.repo.fork == true
      && !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Check author trust / label gate
        id: gate
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request
            const trusted = ["OWNER","MEMBER","COLLABORATOR"].includes(pr.author_association)
            const labels = (pr.labels || []).map(l => l.name)
            const okToTest = labels.includes("ok-to-test")
            if (!(trusted || okToTest)) {
              core.setFailed("Not trusted: require member/collaborator or 'ok-to-test' label.")
            }

      # フォークコードは checkout しない（任意コード実行を避ける）

      - name: Create or update '@codex review' comment
        if: steps.gate.outcome == 'success'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @codex review
          comment-author: 'github-actions[bot]'
          edit-mode: replace
